---
name: "Setup Cloe"
author: Yevhen Fabizhevskyi
description: "This action installs cloe."
branding:
  icon: terminal
  color: gray-dark
inputs:
  force:
    description: |
      If "false" skips installation if cloe is already installed. If "true"
      installs cloe in any case. Defaults to "false".
    required: false
    default: "false"
outputs:
  installed:
    description: Whether cloe was installed or not.
    value: "${{ steps.install-cloe.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./validate-inputs.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: ${{ github.action_path }}/src

    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./collect-info.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"

    - name: Download Cloe
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: cloe-lang/cloe
        fetch-depth: 1
        path: ${{ steps.info.outputs.bin-dir }}

    - name: Install cloe
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-cloe
      run: |
        rake build
        echo "$(pwd)/bin" >> "$GITHUB_PATH"
      shell: sh
      working-directory: ${{ steps.info.outputs.bin-path }}

    - name: Print version
      run: cloe --version
      shell: sh
